.TH IMAGINATION 1 "2009-2018" "3.4" "slide show maker"
.SH "NAME"
Imagination \- A fast and lightweight slide show maker developed with GTK+2 and Cairo.
.SH "SYNOPSIS"
.B imagination [slideshow_project]
.SH "DESCRIPTION"
.PP
.B Imagination
is an easy-to-use application which allows users to create slide shows
from a set of pictures in a very simple way. It uses ffmpeg to produce the
final vob file and libsox to handle the audio files. The vob file can be
burned to a DVD with another application. Exporting of the slideshow as OGV
(Theora/Vorbis) and FLV format is supported as well .
.PP
.B Imagination
has been written in C and GTK+2, and after installing the application you can
run it from the 
.B Applications
menu.
.SH "SEE ALSO"
For further information visit
.I http://imagination.sourceforge.net
.SH "AUTHOR"
Imagination was written by Giuseppe Torelli and
Tadej Borovšak.
.PP
This manual page was written by Alessio Treglia <quadrispro@ubuntu.com>,
for the Ubuntu project (and may be used by others).
